#include <fcntl.h>
#include <locale.h>
#include <stdio.h>

#define PRINT_JULIA_CONST(X) printf("const JL_" #X " = %d\n", X)

int
main(void)
{
    PRINT_JULIA_CONST(LC_ALL);
    PRINT_JULIA_CONST(LC_COLLATE);
    PRINT_JULIA_CONST(LC_CTYPE);
    PRINT_JULIA_CONST(LC_MONETARY);
    PRINT_JULIA_CONST(LC_NUMERIC);
    PRINT_JULIA_CONST(LC_TIME);

    PRINT_JULIA_CONST(O_WRONLY);
    PRINT_JULIA_CONST(O_RDONLY);
    PRINT_JULIA_CONST(O_RDWR);
    PRINT_JULIA_CONST(O_APPEND);
    PRINT_JULIA_CONST(O_CREAT);
    PRINT_JULIA_CONST(O_EXCL);
    PRINT_JULIA_CONST(O_TRUNC);
#ifdef O_TEMPORARY
    PRINT_JULIA_CONST(O_TEMPORARY);
#endif
#ifdef O_SHORT_LIVED
    PRINT_JULIA_CONST(O_SHORT_LIVED);
#endif
#ifdef O_SEQUENTIAL
    PRINT_JULIA_CONST(O_SEQUENTIAL);
#endif
#ifdef O_RANDOM
    PRINT_JULIA_CONST(O_RANDOM);
#endif

    return 0;
}
